version: '3'

services:
  angular:
    build: .
    ports:
      - 80:80
    volumes:
      - ./dist:/usr/share/nginx/html
    depends_on:
      - nginx
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./dist:/usr/share/nginx/html
